### ISSUE TITLE
moving this repo under the jenkinsci umbrella?

### ISSUE THREAD

**Issue by gliptak** [lukanus/git-parameter#10]
Would you please consider moving this plugin under

https://github.com/jenkinsci

Thanks

**Comment by ngiger** [comment]
Done. See version 0.3.2 under https://wiki.jenkins-ci.org/display/JENKINS/Git+Parameter+Plugin.
Can you close this issue as I have no committer right here? Thanks in advance.

**Comment by gliptak** [comment]
Thanks
