### ISSUE TITLE
SSH Environment is not setup before trying to present parameters. (tags)

### ISSUE THREAD

**Issue by TJM** [lukanus/git-parameter#14]
Even though the GIT SCM module has the ability to provide "credentials" (SSH key) for the repository, the git-parameter plugin doesn't seem to use them. The only way we have been able to get it to work is to configure the jenkins user (at the shell) to have a passwordless SSH key with access to the repo. Once the "build" starts, it appears to properly setup the ssh-agent, and further repository access  works using the correct credentials.

**Comment by ngiger** [comment]
https://github.com/jenkinsci/git-parameter-plugin.git. 
Could you please file your bug again under via the issues button in https://wiki.jenkins-ci.org/display/JENKINS/Git+Parameter+Plugin?
Thanks in advance

**Comment by TJM** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-23396 <-- someone beat me to it :)
