### ISSUE TITLE
Work with "Multiple SCM" plugin

### ISSUE THREAD

**Issue by jordiclariana** [lukanus/git-parameter#19]
Hi,

I'm using the "Multiple SCM" plugin and I want add a Git Parameter that acts over one of the Git repo I configured in the "Multiple SCM". The ideal would be to choose one of the multiple git repo configured and over that, the usual parameters from "Git Parameter" plugin.

Is it possible?

**Comment by Zitrax** [comment]
I don't think it's possible currently - I recently commented about the same [here](https://issues.jenkins-ci.org/browse/JENKINS-33584?focusedCommentId=255227&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-255227).

**Comment by ryzn0518** [comment]
The same problem,and when clicking on "Build with Parameters" I had an error:
`!No Git repository configured in SCM configuration.`
Could you please, add a possibility to connect "Git Parameter" with "Multiple SCMs Plugin".
