### ISSUE TITLE
Add refresh button to reload tags

### ISSUE THREAD

**Issue by Matumba2** [lukanus/git-parameter#21]
I'm using this plugin for a Job wich can build different Projects. For this purpose i've added a selection list as a Parameter where i can choose which repository i want to build.
The selected repository will be saved as an Environment Parameter.

In the sourcecode-management section im using this Environment variable to configure the URL of the target repository.

For this purpose it would be great to have a refresh button which reloads the repository URL and updates the list with the available revisions.

**Comment by dizzydis** [comment]
Was there any feedback on this?
