### ISSUE TITLE
tag set but not used

### ISSUE THREAD

**Issue by trumbitta** [lukanus/git-parameter#8]
I'm able to set a tag parameter in configuration and at build time Jenkins asks me to choose one of the tags.

BTW, after that step Jenkins proceeds building master instead of the chosen tag.

Jenkins 1.481
Oracle Java 1.7.0_07
Git 1.7.9.5
Maven 2.2.1

Ubuntu 12.04 LTS

**Comment by trumbitta** [comment]
nvm, I had misunderstood how to use it.

Maybe some quick intro help text could be useful?

**Comment by ngiger** [comment]
Done. By adding the following help text to the Git-Parameter plugin when configuring a project.
See version 0.3.2 under https://wiki.jenkins-ci.org/display/JENKINS/Git+Parameter+Plugin.
Can you close this issue as I have no committer right here? Thanks in advance.

HelpText is:
When used, this parameter will present a build-time a choice to select a Git tag (or revision number) which set a parameter for parametrized build.
Be aware that git does not allow us get additional information (like author/commmit date) from a remote URL this plugin will silently clone the project when you your workspace is empty. This may take a long time when we have a slow connection and/or the checkout is big.
Your workspace is empty when you start the first build or when you have explicitely deleted the workspace.
Often the parameter defined in the "Name" field is used to specify the branch of the git checkout.

**Comment by trumbitta** [comment]
Thanks :)

**Comment by TJM** [comment]
Honestly, I don't think the help text really helped me. I found a blog that half helped, but the comments in it were what finally led me to put "${RELEASE}" into the "Branch" field of the SCM plugin (of course "RELEASE" was the name of my git parameter). In case anyone else stumbles in here too, that is the key to getting it to switch to the tag/revision that you have selected in the git parameter plugin.
